name = "gcbf-church-portal"
compatibility_date = "2024-09-02"
pages_build_output_dir = "dist"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "gcbf_church_db"
database_id = "ee5ba803-39cf-40a4-80f6-b369a2d6a9da"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "gcbf-files"
