name = "gcbf"
main = "worker.js"
compatibility_date = "2024-09-02"

# Assets configuration - serve static files from dist folder
[assets]
directory = "./dist"

# D1 Database binding (used by API routes)
[[d1_databases]]
binding = "DB"
database_name = "gcbf_church_db"
database_id = "ee5ba803-39cf-40a4-80f6-b369a2d6a9da"

# R2 Storage for newsletters, PDFs, and images
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "gcbf-files"

